spring.application.name=resume
gemini.api.key=AQ.Ab8RN6L9D6I9-ch2kkH_L738cp32YwMybA7ceEZ75RuWawrckw
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent
