spring.application.name=resume

# Gemini API Configuration
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent

# Database Configuration
spring.datasource.url=jdbc:h2:file:./data/resumedb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update

# H2 Web Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console