package com.resumecreator.resume.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.resumecreator.resume.agent.ContentAgent;
import com.resumecreator.resume.agent.FormattingAgent;
import com.resumecreator.resume.agent.ValidationAgent;
import com.resumecreator.resume.model.ResumeRequest;

/**
 * ResumeService - Orchestrates the agent pipeline
 * 
 * ARCHITECTURE:
 * This service uses the Agent Design Pattern where 3 specialized agents
 * work together in sequence to create a complete resume.
 * 
 * FLOW:
 * User Input → ContentAgent → FormattingAgent → ValidationAgent → Final Resume
 */
@Service
public class ResumeService {

   @Autowired
   private ContentAgent contentAgent;
   
   @Autowired
   private FormattingAgent formattingAgent;
   
   @Autowired
   private ValidationAgent validationAgent;
    
   /**
    * Main resume generation pipeline
    * 
    * LOGIC:
    * 1. ContentAgent generates raw content from user details
    * 2. FormattingAgent transforms it into professional format
    * 3. ValidationAgent checks quality and provides feedback
    * 
    * SYNTAX:
    * Each step calls the previous agent's output
    * Agents run sequentially (not parallel) to ensure quality
    */
   public String generateResume(ResumeRequest request) {
       // Step 1: Generate content
       String content = contentAgent.generateContent(request);
       System.out.println("✓ Step 1: Content Generated by ContentAgent");
       
       // Step 2: Format the content
       String formattedResume = formattingAgent.formatResume(content);
       System.out.println("✓ Step 2: Resume Formatted by FormattingAgent");
       
       // Step 3: Validate the resume
       String validationResult = validationAgent.validateResume(formattedResume);
       System.out.println("✓ Step 3: Resume Validated by ValidationAgent");
       
       // Return the formatted resume (validation feedback can be stored separately)
       return formattedResume;
   }
   
   /**
    * Get validation feedback for a resume
    * Useful for getting improvement suggestions without the full resume
    */
   public String getValidationFeedback(ResumeRequest request) {
       String content = contentAgent.generateContent(request);
       String formattedResume = formattingAgent.formatResume(content);
       return validationAgent.validateResume(formattedResume);
   }

}
