package com.resumecreator.resume.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import com.resumecreator.resume.agent.InterviewQuestionAgent;
import com.resumecreator.resume.agent.QualityReviewAgent;
import com.resumecreator.resume.agent.ResumeGeneratorAgent;
import com.resumecreator.resume.agent.RevisionAgent;
import com.resumecreator.resume.model.QualityReviewResult;
import com.resumecreator.resume.model.Resume;
import com.resumecreator.resume.model.ResumeRecord;
import com.resumecreator.resume.model.ResumeRequest;
import com.resumecreator.resume.model.ResumeResponse;
import com.resumecreator.resume.repository.ResumeRecordRepository;
import com.resumecreator.resume.validator.ResumeLengthValidator;

@Service
public class ResumeService {

    private static final int MAX_REVISIONS = 2;

    @Autowired private ResumeGeneratorAgent generatorAgent;
    @Autowired private QualityReviewAgent qualityReviewAgent;
    @Autowired private ResumeLengthValidator lengthValidator;
    @Autowired private RevisionAgent revisionAgent;
    @Autowired private InterviewQuestionAgent interviewQuestionAgent;
    @Autowired private ResumeRecordRepository resumeRecordRepository;

    private final ObjectMapper mapper = new ObjectMapper();

    public ResumeResponse generateResume(ResumeRequest request) {
        // Step 1: generate + format (llm call 0)
        String resumeJson = generatorAgent.generateResume(request);
        System.out.println("✓ Step 1: Resume generated by ResumeGeneratorAgent");

        int attempts = 0;
        int lastKnownScore = 0;

        while (attempts < MAX_REVISIONS) {
            // Step 2: quality review — checks claims + bullets (llm call 1)
            QualityReviewResult review = qualityReviewAgent.review(resumeJson, request);
            lastKnownScore = review.getOverallScore();
            System.out.println("✓ Step 2: Reviewed — score=" + lastKnownScore
                    + " decision=" + review.getDecision());
            System.out.println("Unsupported claims: " + review.getUnsupportedClaims()); 
            System.out.println("Bullet issues: " + review.getBulletIssues());  
            System.out.println("Suggested improvements: " + review.getImprovements());     

            // Step 3: length check — plain Java, free, always runs
            boolean lengthOk = lengthValidator.isValid(resumeJson);
            String lengthFeedback = lengthValidator.getFeedback(resumeJson);
            System.out.println("✓ Step 3: Length check — " + lengthFeedback);

            boolean needsRevision = "REVISE".equals(review.getDecision()) || !lengthOk;

            if (!needsRevision) {
                System.out.println("✓ Resume approved, no revision needed");
                break;
            }

            // Step 4: revise, then loop back to review again
            System.out.println("↻ Revising (attempt " + (attempts + 1) + ")");
            resumeJson = revisionAgent.revise(resumeJson, review, lengthFeedback);
            attempts++;
            
        }

        // Step 5: interview questions on the final resume
        String questionsJson = interviewQuestionAgent.generateQuestions(resumeJson);
        System.out.println("✓ Step 5: Interview questions generated");

        // Step 6: parse both final strings into real objects for the API response
        ResumeResponse finalResponse = buildResponse(resumeJson, questionsJson, request);

        // Step 7: save the final resume to the database
        saveToDatabase(request, finalResponse, lastKnownScore);

        return finalResponse;
    }

    private ResumeResponse buildResponse(String resumeJson, String questionsJson, ResumeRequest originalRequest) {
        Resume parsedResume;
        List<String> parsedQuestions;

        try {
            parsedResume = mapper.readValue(resumeJson, Resume.class);
        } catch (Exception e) {
            System.out.println("✗ Failed to parse final resume JSON: " + e.getMessage());
            ResumeResponse errorResponse = new ResumeResponse();
            errorResponse.setError("Resume was generated but could not be parsed into structured JSON: " + e.getMessage());
            return errorResponse;
        }

        // DETERMINISTIC FIX: contact info is fixed user data, not LLM-generated content.
        // Regardless of what any LLM step did to this section, force it back to the
        // original request's values so it can never be blank, altered, or dropped.
        Resume.ContactInformation contact = parsedResume.getContactInformation();
        contact.setName(originalRequest.getName());
        contact.setEmail(originalRequest.getEmail());
        contact.setPhone(originalRequest.getPhone());

        // NEW: catch the "parsed successfully but suspiciously empty" case
        if (parsedResume.getExperience().isEmpty() && parsedResume.getProjects().isEmpty()) {
            System.out.println("⚠ Warning: parsed resume has no experience or project content despite successful parsing");
        }   

        try {
            parsedQuestions = mapper.readValue(questionsJson, new TypeReference<List<String>>() {});
        } catch (Exception e) {
            System.out.println("✗ Failed to parse interview questions JSON: " + e.getMessage());
            parsedQuestions = List.of(); // non-fatal — resume is still usable without questions
        }

        return new ResumeResponse(parsedResume, parsedQuestions);
    }

    // public QualityReviewResult getValidationFeedback(ResumeRequest request) {
    //     String resume = generatorAgent.generateResume(request);
    //     return qualityReviewAgent.review(resume, request);
    // }

    private void saveToDatabase(ResumeRequest request, ResumeResponse response, int score) {
        try {
            String requestJson = mapper.writeValueAsString(request);
            String responseJson = mapper.writeValueAsString(response);
            ResumeRecord record = new ResumeRecord(request.getName(), requestJson, responseJson, score);
            resumeRecordRepository.save(record);
            System.out.println("✓ Step 7: Resume saved to database, id=" + record.getId());
        } catch (Exception e) {
            System.out.println("✗ Failed to save resume to database: " + e.getMessage());
        }
    }
}