package com.resumecreator.resume.agent;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.resumecreator.resume.client.LLMClient;
import com.resumecreator.resume.model.QualityReviewResult;

@Component
public class RevisionAgent {

    @Autowired
    private LLMClient llmClient;

    public String revise(String resumeContent, QualityReviewResult issues, String lengthFeedback) {
        // Sanitize strings to escape any literal '%' generated by LLM feedback
        String safeResume = sanitize(resumeContent);
        String safeClaims = sanitize(issues.getUnsupportedClaims() != null ? issues.getUnsupportedClaims().toString() : "");
        String safeBullets = sanitize(issues.getBulletIssues() != null ? issues.getBulletIssues().toString() : "");
        String safeLength = sanitize(lengthFeedback);

        String prompt = """
            You are an expert, strict resume editor. Your job is to revise an existing resume based ONLY on specific feedback.

            CRITICAL CONSTRAINTS:
            1. DO NOT fabricate, invent, or add any new facts, metrics, skills, or work experience that are not in the original resume.
            2. Preserve the original voice, facts, and structure unless explicitly directed to fix them.
            3. STRUCTURE PRESERVATION IS MANDATORY: The output JSON MUST retain every field from the
               input, fully populated — contact_information (name, email, phone), summary, skills,
               experience (each entry keeping role, company, period, and bullet_points),
               projects (each entry keeping title, technologies, and bullet_points), and education.
               NEVER return an empty array or blank string for a field that had content in the input,
               unless that specific content was flagged as an unsupported claim to remove.
            4. EXACT KEY NAMES ONLY: You MUST use the exact field names shown in the schema below.
               Do NOT substitute synonyms. Specifically: use "period" (NEVER "duration"), and use
               "bullet_points" (NEVER "bullets" or "highlights"). Using a different key name than the
               schema is treated as deleting that field's data.
            5. If a project's "technologies" array was populated in the input, it MUST remain populated
               and unchanged in the output — do not drop it while editing other fields on that project.
            6. If you need to increase length, do so by ADDING more bullet points or more detail to
               EXISTING bullet points — never by leaving bullet_points, title, role, company, period,
               or technologies blank.
            7. OUTPUT FORMAT: Return ONLY a valid JSON object matching the input structure. Do not include markdown code blocks (like ```json), intro text, or conversational filler.

            REQUIRED JSON SCHEMA (use these EXACT key names, no synonyms):
            {
              "contact_information": { "name": "", "email": "", "phone": "" },
              "summary": "",
              "skills": ["string"],
              "experience": [
                { "role": "", "company": "", "period": "", "bullet_points": ["string"] }
              ],
              "projects": [
                { "title": "", "technologies": ["string"], "bullet_points": ["string"] }
              ],
              "education": ["string"]
            }

            INPUT RESUME:
            %s

            FEEDBACK TO APPLY:
            - Remove or tone down these unsupported claims: %s
            - Strengthen these specific bullet points without inventing false metrics: %s
            - Length adjustment guidance: %s

            REVISION INSTRUCTIONS:
            - For unsupported claims: Remove the exaggerated wording or ground them in facts provided in the text.
            - For weak bullets: Rewrite them using strong action verbs while maintaining factual accuracy.
            - For missing required fields: Add them back into the contact_information section without altering any other content.
            - If the resume is too short: expand existing bullet points with more specific detail, or add
              1 additional bullet point per experience/project entry. Do not remove or blank any existing field.
            - If the resume is too long: tighten wording within bullet points. Do not delete entire bullet
              points, titles, roles, company/period, or technologies fields.
            """.formatted(
                safeResume,
                safeClaims,
                safeBullets,
                safeLength
            );

        return llmClient.callLLM(prompt);
    }

    private String sanitize(String input) {
        if (input == null) return "";
        // Replaces literal '%' with '%%' so Java String.formatted doesn't mistake it for a format specifier
        return input.replace("%", "%%");
    }
}